name: conquest
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

#-------------------PACKAGES---------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  flutter_native_splash: ^2.3.1
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  carousel_slider: ^5.0.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  page_transition: ^2.1.0
  favorite_button: ^0.0.4
  readmore:
  flutter_rating_bar:
  bottom_nav_layout:
  cached_network_image: ^3.4.0

  # Location & Address
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  uuid: ^4.5.0


  # Firebase Packages
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.0.3
  google_sign_in: ^6.2.1

  # State Management
  get: ^4.6.6


#-------------------PACKAGES END---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  #-------------------LOCAL ASSETS---------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/appicons/
    - assets/icons/drawerIcons/
    - assets/icons/bottomNavbaricons/InactiveIcons/
    - assets/icons/bottomNavbaricons/activeIcons/



#-------------------LOCAL FONTS---------------#
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800




























